### ISSUE TITLE
Phase1 - Bugs 

### ISSUE THREAD

**Issue by orayaintbizth** [orayaintbizth/BuffoHero#1]
[ฝั่งผู้ประกาศงาน]
- [x] 1. ตอนสมัครของผู้ประกาศงาน ไม่สามารถใส่รูปบริษัทได้
- [x] 2. กรอกประกาศงาน ช่องรายละเอียดงาน ไม่สามารถจัดอักษรได้อย่างอิสระ เช่น ปรับขนาดฟ้อนต์ไม่ได้ พอเลือก Formats แล้ว ในแต่ละบรรทัดจะได้ขนาดไม่เท่ากัน
- [x] 3. บางครั้งประกาศงานในหมวดเด็กฝึกงานไม่ได้ ระบบแจ้งว่า
  Fuel\Core\PhpErrorException [ Notice ]:
  Undefined offset: 27

<s> - [ ] 4. ประกาศงานจะไม่สามารถเพิ่มรูปได้ </s>
<s> - [ ] 5. ประกาศงานในหมวดงานประจำ ฟรีแลนซ์ได้ แต่ใส่รูปไม่ได้ เมื่อประกาศเสร็จ ในหน้า complete จะไม่สามารถกดโพสต์งานได้ ต้องไปที่ดูตำแหน่งงานก่อน </s>
<s> - [ ] 6. แก้ไขงานด้วยการเพิ่มรูปไม่ได้ </s>
- [x] 7. ในการประกาศงานประจำและฟรีแลนซ์ ช่อง พื้นที่ทำงาน, คุณสมบัติ, ทักษะที่จำเป็น ระบบไม่ขึ้นข้อมูลอัตโนมัติเหมือนของหมวดฝึกงาน
- [x] 8. การตั้งค่า เปลี่ยนรหัสผ่านไม่ได้
- [x] 9. ส่งข้อความ จากผู้ประกาศไปยังผู้สมัคร อยากให้ระบบแจ้งเตือนหรือมี popup ที่ขึ้นว่าส่งข้อความแล้ว ชัดเจนกว่านี้
- [x] 10. กล่องข้อความ อยากให้มีดูข้อความที่ส่งแล้วได้
- [x] 11. หากล็อคอินด้วย account ผู้ประกาศงาน เมื่อเข้าหน้าแรกเพื่อค้นหางานหรือชื่อบริษัท จะไม่ได้สามารถทำได้
- [x] 12. กดปุ่มโพสต์งานจากหน้าต่างๆ อาทิ หน้ารายการที่ฝึกงาน หน้า dashboard ไม่ได้
- [x]  13. ตรงโพสฝึกงาน  ตรงรายละเอียด พอพิมยาวๆแล้วมัน  แสดงผลออกมาแล้วไม่จัด  เปนขึ้นบรรทัดใหม่ให้  ยกเว้นเราจะพิมขึ้นบรรทัดใหม่เอง ตอนแก้ไขรายละเอียด
  ![image](https://cloud.githubusercontent.com/assets/12592502/7793981/f2c4b974-02ef-11e5-93fd-6fa9526760d6.png)
- [x] 14. กดเปลี่ยนภาษาเป็นภาษาอังกฤษ  เเต่บางส่วนยังไม่เปลียน เป็นใน IE, Firefox  เช่นดูประกาศงานของคุณ
  ![image](https://cloud.githubusercontent.com/assets/12592502/7794719/91e4fa1c-02f7-11e5-85ff-3f51b3171e5b.png)
- [x] 15. เพิ่มงานฟรีเเลนซ์เเล้ว พอกดค้นหาฟรีแลนซ์จ๊อบจะไม่เจองานนั้นๆ ทั้งๆที่ใส่แท็กแล้วพอกดแท็กไปก็หาไม่เจอ (ตัวอย่างงาน ช่างภาพ ไม่สามารถค้นหาเจอและค้นหาด้วยแท็กไม่ได้)
  ![image](https://cloud.githubusercontent.com/assets/10752242/7808444/7e139da6-03bd-11e5-9e71-012594a77ee3.png)
  ![screen shot 2558-05-26 at 3 41 31 pm](https://cloud.githubusercontent.com/assets/10752242/7808488/cb303ba8-03bd-11e5-8a25-a415d71fcd52.png)
- [x] 16. อันนี้รบกวนเปลี่ยนรูป buffo หน้าแรกให้เป็นรูปจูงเด็กนักศึกษาไทย ให้ด้วยค่ะ รูปส่งไปในเมล์แล้ว
  ![image](https://cloud.githubusercontent.com/assets/10752242/7808930/e0d44fe6-03c0-11e5-9a80-62e2e4821e96.png)

---

[ฝั่งผู้หางาน]
- [x] 1. ค้นหางานไม่ได้ เช่น ค้นว่า sale แต่พอหาจริง ได้ตำแหน่งงานอื่นแทน

@songsakn @liverbool @sasiwimon-intbizth @apisakN @JRWNKh

**Comment by liverbool** [comment]
:+1: @orayaintbizth

**Comment by freelance724** [comment]
[ฝั่งผู้ประกาศงาน]
1. upload ได้อยู่แล้วหรือป่าว เห็นรูปใช้ได้แล้ว
2. เพิ่ม css (ul, ol) ให้ ของเก่าน่าจะเป็นแบบนี้อยู่แล้ว ไม่ได้แก้อะไรเพิ่มเติม
3. ต้องขอรูปภาพประกอบเพิ่มจะได้รู้ว่าเป็นที่ตรงไหน
4. help บนหน้าจอบอกว่า "รองรับแค่ .doc หรือ .pdf เท่านั้น และมีขนาดไม่เกิน 5MB" เลยไม่น่าอัพโหลดรูปได้หรือป่าว
5. เหตุผลเหมือนข้อ 4 เพิ่ม การ post งานเพิ่มให้อีก ไม่น่าใช่ bug ( new requirement ? )
6. เหตุผลเหมือนข้อ 4
7. เป็น bug จริงๆ แก้ไขให้แล้ว
8. เท่าที่ลองทดสอบดูใช้ได้ไม่มี bug ครับ
9. เพิ่ม alert แบบ bootstrap ให้แล้ว
10. เพิ่มให้แล้วครับ
11. เป็น bug จริงๆ แก้ไขให้แล้ว
12. ของเดิมมีปุ่ม "เพิ่มตำแหน่งงานใหม่" อยู่แล้วหรือป่าวครับ ถ้าอยากได้เป็น link หรือ ปุ่มในส่วนไหน ต้องบอกเพิ่ม
[ฝั่งผู้หางาน]
1. เท่าที่ดูข้อมูล job salary ของอันนี้เป็น 125,698 แต่หน้าจอ filter ได้แค่ 100,000

ref: https://github.com/intbizth/Buffohero---Web-Development/commit/6662f6cd6e343ea6c013fce7a2c4c1e0e38c254f

**Comment by JRWNKh** [comment]
-  ตรงโพสฝึกงาน  ตรงรายละเอียด พอพิมยาวๆแล้วมัน  แสดงผลออกมาแล้วไม่จัด  เปนขึ้นบรรทัดใหม่ให้  ยกเว้นเราจะพิมขึ้นบรรทัดใหม่เอง ตอนแก้ไขรายละเอียด
![image](https://cloud.githubusercontent.com/assets/12592502/7793981/f2c4b974-02ef-11e5-93fd-6fa9526760d6.png)

-

**Comment by JRWNKh** [comment]
- กด  เปลี่ยนภาษาเปนภาษาอังกฤษ  เเต่บางส่วนยังไม่เปลียน  เช่นดูประกาศงานของคุณ
![image](https://cloud.githubusercontent.com/assets/12592502/7794719/91e4fa1c-02f7-11e5-85ff-3f51b3171e5b.png)

-แนบไฟล์ไม่ได้   ตอนโพสประกาศงาน  มีการให้เพิ่มไฟล์เเนบแต่ตอนเเสดงผลหน้าเว็บ  ไม่มีไฟล์เเนบให้เหนรายละเอียดงาน

-เพิ่มงานฟีเเลนเเล้วมันไม่ขึ้น  ตรง หางาน >>freelandjob  มันหาไม่เจอ

**Comment by JRWNKh** [comment]
- การจัดหมวดหมู่ย่อยดูยาก   น่าจะเเยก  หมวดหมู่ย่อยๆ  ไปทางฝั่งเดียวกัน
![image](https://cloud.githubusercontent.com/assets/12592502/7795047/3f5e0352-02fb-11e5-9254-e3f114b7e977.png)

**Comment by orayaintbizth** [comment]
[ฝั่งผู้ประกาศงาน]
เหลือข้อ 13, 14, 15, 16 นะคะ รบกวนฟีดแบคให้หน่อยนะคะ

[ฝั่งผู้หางาน]
- [ ] 1. ค้นหางานไม่ได้ เช่น ค้นว่า sale แต่พอหาจริง ได้ตำแหน่งงานอื่นแทน
- เท่าที่ดูข้อมูล job salary ของอันนี้เป็น 125,698 แต่หน้าจอ filter ได้แค่ 100,000

อันนี้คือสามารถแก้ไขให้เห็นทั้งหมดได้ไหมค่ะ

@songsakn

**Comment by freelance724** [comment]
แก้ไข 13, 14, 16 ให้แล้วจ้า

to: @orayaintbizth
ref: https://github.com/intbizth/Buffohero---Web-Development/commit/99e0dccbb7b21d75a3102038ed6e200bad258263

**Comment by freelance724** [comment]
ข้อ 15 แก้ไขให้แล้ว (เปลี่ยนไปใช้หน้า search เดียวกัน)
ref: https://github.com/orayaintbizth/BuffoHero/issues/3

**Comment by freelance724** [comment]
[ฝั่งผู้หางาน]
ข้อ 1 ก็น่าจะโอเคแล้วนะ รบกวน close ให้ด้วยแพร์

**Comment by orayaintbizth** [comment]
ปิดให้แล้วนะคร้าา

2015-06-04 11:53 GMT+07:00 songsakn notifications@github.com:

> [ฝั่งผู้หางาน]
> ข้อ 1 ก็น่าจะโอเคแล้วนะ รบกวน close ให้ด้วยแพร์
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/orayaintbizth/BuffoHero/issues/1#issuecomment-108721135
> .

## 

---

Best Regards,
Oraya Amaritherun (Prae)
Account Executives & Project Manager.

Intelligence Business (Thailand) Co., Ltd.
2/119  Rat Phatthana Rd., Saphan Sung,
Saphan Sung, Bangkok, 10240
Tel.        02-115-9907
Fax        02-115-9908
Mobile    089-123-5016

## E-mail    oraya@intbizth.com

Visit our site at www.intbizth.com
Follow our Twitter @intbizth
Become our fan : www.facebook.com/Intbizth

---

## Intelligence Business (Thailand) Company Limited Disclaimer

Intelligence Business (Thailand)  Company Limited treats all of the
information in this e-mail as only allegation, opinions, or discussions and
makes absolutely no claims whatsoever for the substance or the factual or
conceptual accuracy of any informaion, statement, documents, image or other
material of any nature whatsoever which is contained in this e-mail sent
for the non-business affairs of the company, individual purpose and /or on
individual own name.
This e-mail is confidential. It may also be legally privileged. The
recipient is not allowed to distribute, copy, revise, retransmit,
disseminate or use this e-mail or any part of it in any form whatsoever for
any purpose.
