### ISSUE TITLE
Phase1 - New Requirement 

### ISSUE THREAD

**Issue by orayaintbizth** [orayaintbizth/BuffoHero#2]
- [x] 1. เพิ่มการแนบรูปภาพในการประกาศงาน โดยการประกาศ 1 ครั้ง สามารถเพิ่มไฟล์นามสกุล .doc, .docx .pdf, .jpg, .jpeg ได้ทั้งหมด 3 ไฟล์
- [x] 2. สำหรับคนหางานหรือที่ฝึกงานจะต้องล็อคอินเข้ามาก่อน ถึงจะเห็นเบอร์โทรติดต่อ อีเมล์ ถ้าไม่ล็อคอินเข้ามาก็จะเห็นแค่ชื่อบริษัม รายละเอียด แต่ไม่เห็นเบอรืหรืออีเมล์ติดต่อ
- [x] 3. เปลี่ยนคำว่า Dashboard เป็นคำว่า Profile แทน
- [x] 4. ย้ายปุ่มโพสต์งานไปไว้แถวเดียวกับ Profile โดยอยู่แถวที่ 2 ระหว่าง Prile กับออกจากระบบ
- [x] 5. ลบปุ่มแก้ไขเรซูเม่ออก
  ![image](https://cloud.githubusercontent.com/assets/10752242/7808772/ceaa51cc-03bf-11e5-8f9d-d6bda16bf40b.png)

cc : @songsakn @liverbool @sasiwimon-intbizth @apisakN @JRWNKh

**Comment by freelance724** [comment]
แก้ไขข้อ 3,4,5 ให้แล้วจ้า

ref: https://github.com/intbizth/Buffohero---Web-Development/commit/99e0dccbb7b21d75a3102038ed6e200bad258263

**Comment by freelance724** [comment]
เพิ่ม 1, 2 ให้แล้วครับ

**Comment by orayaintbizth** [comment]
พี่เซี๊ยะคะ

ข้อ 2. แพร์รบกวนให้ซ่อนสิ่งที่แนบมาด้วยได้ไหมค่ะ คือถ้าไม่ล็อคอินเข้ามาก็ดุไฟลืแนบไม่ได้ด้วยเช่นกันอะค่ะ

**Comment by freelance724** [comment]
แก้ ข้อ 2 เพิ่มให้แล้วครับ

ref: https://github.com/intbizth/Buffohero---Web-Development/commit/397ab298915cc8e8a1b422bc6b45bc8d030642d1
