### ISSUE TITLE
Phase1 - New Search

### ISSUE THREAD

**Issue by orayaintbizth** [orayaintbizth/BuffoHero#3]
- [x] 1. ระบบ search เอาแนวๆ นี้ไหม 
  ส่วนตัวชอบแบบของ job bkk นะ พี่เซี๊ยะคิดว่าไงบ้างฮะ 

![screen shot 2558-05-27 at 10 53 05 am](https://cloud.githubusercontent.com/assets/10752242/7828894/4bbe9908-0464-11e5-9a75-1ca60ae00dea.png)

![screen shot 2558-05-27 at 10 57 50 am](https://cloud.githubusercontent.com/assets/10752242/7828895/5547b3c4-0464-11e5-8939-fcded4d8e323.png)

![screen shot 2558-05-27 at 11 31 43 am](https://cloud.githubusercontent.com/assets/10752242/7828896/5c1ba4c6-0464-11e5-8645-e24546f0c64e.png)

@songsakn @liverbool @sasiwimon-intbizth @apisakN @JRWNKh

**Comment by orayaintbizth** [comment]
พี่เซี๊ยะ @songsakn คะ 

ถ้าเอาตามแบบนี้พอเป็นไปได้ไหมค่ะ

Search แบบธรรมดา
- มีช่องค้นหา โดยสามารถค้นหาจากตำแหน่งหรือคีย์เวิร์ดได้

Search แบบพิเศษ (อยู่ตำแหน่งเดิมทางซ้าย)
- ประเภทงาน (มีฝึกงาน, งานประจำ, ฟรีแลนซ์ โดยต้องเลือกประเภทงานก่อน ถึงจะเลือกช่องต่อไปได้)
- หมวดหมู่งาน (ต้องเลือกหมวดหมู่งานก่อน ถึงจะเลือกช่องต่อไปได้)
- หมวดหมู่งานย่อย
- เงินเดือน
- สถานที่ปฏิบัติงาน
- คุณสมบัติ
- ทักษะ

**Comment by freelance724** [comment]
ทำการเพิ่มให้แล้วครับ

ref: https://github.com/intbizth/Buffohero---Web-Development/commit/7993b5aaa0a6f720e754e578b9883a4ac55a87ea
