### ISSUE TITLE
Phase1 - Bugs 3

### ISSUE THREAD

**Issue by orayaintbizth** [orayaintbizth/BuffoHero#6]
@freelance724 @apisakN @ShabooShaboo @MarkRider031

**Comment by selfclose** [comment]
**ฝั่ง ผู้ประกอบการ**
_ทดสอบบน Web browser : Google Chrome_
- [ ] 1. หน้าต่าง Profile หลังจาก Upload ภาพ มีปัญหา Responsive ล้นจาก Div **เมื่อย่อหน้าต่าง**
  ![01](https://cloud.githubusercontent.com/assets/13775594/9266890/66e3771c-4271-11e5-9786-bfe44307c57f.png)
- [ ] 2. จำลองเล่นบนโทรศัพท์ เมนู Avatar มีขอบบังอยู่ 
  ![02](https://cloud.githubusercontent.com/assets/13775594/9266950/320b2958-4272-11e5-9384-6bbf98b9421a.png)
- [ ] 3. บันทึกภาพ PNG ตรงโปร่งใส่ถูกเปลี่ยนเป็นขอบดำแทน
  ![03-1](https://cloud.githubusercontent.com/assets/13775594/9266976/9b003692-4272-11e5-8a4b-ae8e42cbcca6.png)
  ![03-2](https://cloud.githubusercontent.com/assets/13775594/9266977/9b017e80-4272-11e5-8cf2-62b8400dad71.png)
- [ ] 4. เมนู หาคนทำงาน > ฟรีแลนซ์  ไม่มีหน้าเพจ Page
  ![04](https://cloud.githubusercontent.com/assets/13775594/9267006/e0adb8cc-4272-11e5-909e-dc8bdd55ad6b.png)
- [ ] 5. เมื่อลบ “ตำแหน่งงานที่มีในตอนนี้” ออกไปแล้ว  รายชื่องานที่ฝั่งผู้สมัครงานไม่ถูกลบออกจาก "ตำแหน่งงานที่สมัคร" (ยังอยู่)
  ![05](https://cloud.githubusercontent.com/assets/13775594/9267109/b7f7e85c-4273-11e5-910f-5d4075a0bfc5.png)
- [ ] 6. เมื่อจำลองเล่นบนโทรศัพท์บน Chrome ปุ่ม “+เพิ่มในรายการของฉัน” และ ปุ่ม “ดูเรซูเม่” หายไป
  **(แต่ทดสอบบนโทรศัพท์จริง มีทั้ง 2 ปุ่ม แต่ทัชไม่ได้)**
  ![08](https://cloud.githubusercontent.com/assets/13775594/9267218/8e461ea0-4275-11e5-9e04-63513b26c059.png)

_ทดสอบบน IE_
- [ ] 7. บน IE มีอักษรล้นขอบ ในเมนู  _หางาน > ตามบริษัท_
  ![06](https://cloud.githubusercontent.com/assets/13775594/9267149/43bd5b7e-4274-11e5-912d-2e18a7c5c45c.png)
- [ ] 8. บน IE  CSS animation หน้า Home page ไม่ทำงาน
- [ ] 9. ไม่สามารถจัดการ เขียน, ลบ หรือตอบกลับ และผู้สมัครงานไม่สามารถตอบกลับได้
  ![07](https://cloud.githubusercontent.com/assets/13775594/9267196/0e8bc1f6-4275-11e5-90f1-c5fdde2fe31e.png)

**Comment by MarkRider031** [comment]
*****ก่ารใช้งานในฝั่งของ ผู้ใช้งาน
- [ ] 1.ปัญหาในการบันทึกข้อมูล 
       จากการที่เราบันทึกข้อมูลไปในรอบที่1 ข้อมูลที่อยู่ในส่วน ที่อยู่ รหัสไปรษณีย์ ข้อมูลการศึกษา
       ตำแหน่งงานและเงินเดือนที่คาดหวัง ประสบการณ์การทำงาน จะอยู่ในระบบประมาณ 5 นาที 
       จากนั้นจะหายไป  
       แต่ถ้าเราทำการบันทึกข้อมูลอีกครั้ง   ที่อยู่ รหัสไปรษณีย์ ข้อมูลการศึกษา
       ตำแหน่งงานและเงินเดือนที่คาดหวัง ประสบการณ์การทำงาน จะไม่หายไป
      ![image](https://cloud.githubusercontent.com/assets/13775556/9267028/0a175a10-4273-11e5-8362-3794bd91397c.png)
- [ ] 2.ภาษาที่อยู่ใน ทักษะภาษา ถ้าผู้ใช้เลือก ภาษากรีกหรือภาษาอื่นๆ เป็นเมนูภาษาไทย เสร็จแล้วผู้ใช้บันทึกและเลือกเปลี่ยนเมนูเป็นภาษาอังกฤษ ภาษาที่ผู้ใช้เลือกไม่เปลี่ยนเป็นภาษาอังกฤษ ดังภาพ
  
    ![image](https://cloud.githubusercontent.com/assets/13775556/9267217/8b385b92-4275-11e5-8e3e-163fe3c353cd.png)
    ![image](https://cloud.githubusercontent.com/assets/13775556/9267219/8e84e644-4275-11e5-984a-6c8e2d0159ab.png)
  -- แต่ถ้าผู้ใช้ลบคำว่า ภาษากรีกออก จะแลดวงตัวเลือกออกมาเป็นภาษาอังกฤษ
  ![image](https://cloud.githubusercontent.com/assets/13775556/9267427/0032ca2e-4279-11e5-974f-a88ae94f03c4.png)
- [ ] 3.รูปแบบของตัวอักษร ที่มีขนาดเกินจากช่อง
       ![image](https://cloud.githubusercontent.com/assets/13775556/9266998/cb1b4c40-4272-11e5-85aa-0fdc3ae4e7e6.png)
- [ ] 4.ช่วยซ่อน เมนู ช่วยเหลือ ไว้ก่อน 
       ในส่วนของ help ถ้าผุ้ใช้กดเลือกฟังก์ชั่นภาษาอังกฤษ แล้วเลือก เมนู How to purchase ข้อมูลที่อยู่ภายใน               หน้า How to purchase ไม่ถูกเปลี่ยนเป็น ภาษาอังกฤษ และในส่วนของช่วยเหลือ ไม่มีรูปภาพ
  ![image](https://cloud.githubusercontent.com/assets/13775556/9267059/54d9851e-4273-11e5-9a82-42afd3777b67.png)
  ![image](https://cloud.githubusercontent.com/assets/13775556/9267072/62872c7a-4273-11e5-982c-06b568aafd61.png)
  ![image](https://cloud.githubusercontent.com/assets/13775556/9267091/90dcc65c-4273-11e5-8420-8c3c27f6065c.png)
